version: '3.4'

services:
    app_test:
        build:
            context: .
            dockerfile: Dockerfile.development
        links:
            - mailhog_test
            - mysql_test
        ports:
            - "1200:80"
        expose:
            - "80"
            - "443"
        dns:
            - 8.8.8.8
            - 8.8.4.4
        volumes:
            - ../:/app/
            - ./home/application/.bash_history:/home/application/.bash_history
        cap_add:
            - SYS_PTRACE
        privileged: true
        env_file:
            - etc/environment.yml
            - etc/environment.development.yml
        environment:
            - VIRTUAL_HOST=.app.boilerplate.docker
            - VIRTUAL_PORT=80
            - POSTFIX_RELAYHOST=[mail]:1025
        networks:
            app_test_net:
                ipv4_address: 10.10.254.2

    phpmyadmin_test:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql_test
        expose:
            - "80"
        environment:
            - PMA_HOSTS=mysql_test
            - VIRTUAL_HOST=pma.boilerplate.docker
            - VIRTUAL_PORT=80
        volumes:
            - phpmyadmin_test:/sessions
        networks:
            app_test_net:
                ipv4_address: 10.10.254.3

    mailhog_test:
        image: mailhog/mailhog
        expose:
            - "8025"
        environment:
            - VIRTUAL_HOST=mail.boilerplate.docker
            - VIRTUAL_PORT=8025
        networks:
            app_test_net:
                ipv4_address: 10.10.254.4

    mysql_test:
        build:
            context: container/mysql/
            dockerfile: MySQL-5.7.Dockerfile
        command: --sql_mode=""
        expose:
            - "3306"
        volumes:
            - mysql_test:/var/lib/mysql
            - ./backup:/var/backup/
            - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        env_file:
            - etc/environment.yml
            - etc/environment.development.yml
        networks:
            app_test_net:
                ipv4_address: 10.10.254.5

volumes:
    app_test:
    mysql_test:
    phpmyadmin_test:

networks:
    app_test_net:
        driver: bridge
        ipam:
          driver: default
          config:
          - subnet: 10.10.254.0/24
